name: orangecloud_player_demo
description: OrangeCloud Player SDK Flutter Demo
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  orangecloud_player_client:
    git:
      url: https://github.com/OrangeCloud-SDK-Player/orangecloud-player-flutter.git
      ref: v1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
